"""empty message

Revision ID: 1c749403b1b5
Revises: c64d5b3bdd50
Create Date: 2025-04-15 14:41:53.392773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c749403b1b5'
down_revision = 'c64d5b3bdd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
