"""empty message

Revision ID: 363cbf7f5185
Revises: 1c749403b1b5
Create Date: 2025-04-16 21:41:49.277902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '363cbf7f5185'
down_revision = '1c749403b1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.Integer(), nullable=True))
        batch_op.drop_column('dislike')
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dislike', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
